<?php

namespace Database\Seeders;

use App\Models\DailyInsight;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DailyInsightSeeder extends Seeder
{
    public function run(): void
    {
        $insights = [
            'Hari ini adalah awal dari petualangan baru. Jangan takut untuk melangkah.',
            'Kesalahan adalah guru terbaik. Belajarlah darinya dan terus maju.',
            'Kebahagiaan bukanlah tujuan, tetapi perjalanan. Nikmati setiap momen.',
            'Jadilah cahaya bagi orang lain, meski hanya sebatas senyuman.',
            'Terkadang, hal terkecil yang kita lakukan bisa membawa dampak terbesar.',
            'Tidak semua luka terlihat, tetapi setiap perjuangan selalu membentuk pribadi yang lebih kuat.',
            'Hari buruk hanyalah bagian kecil dari perjalanan hidup yang panjang dan bermakna.'.
            'Jangan membandingkan langkah awalmu dengan pencapaian besar milik orang lain.'.
            'Bahagia sering datang saat kamu berhenti mengejar kesempurnaan yang tidak nyata.',
            'Kamu jauh lebih kuat daripada semua keraguan yang pernah menghantuimu selama ini.',
            'Istirahat bukan kelemahan, melainkan cara terbaik memulihkan semangat untuk melangkah kembali.',
            'Kesalahan mengajarkan pelajaran berharga yang tidak pernah diberikan oleh keberhasilan.',
            'Langkah kecil yang konsisten selalu lebih baik daripada rencana besar tanpa tindakan.',
            'Hidup akan terasa lebih ringan ketika kamu belajar menerima kenyataan dengan ikhlas.',
            'Keberanian bukan berarti tidak takut, melainkan tetap melangkah meski merasa takut.',
            'Jangan menyerah hanya karena hasil belum sesuai dengan harapan yang kamu miliki.',
            'Setiap pengalaman sulit menyimpan pelajaran berharga yang akan berguna suatu hari nanti.',
            'Waktu akan memperbaiki banyak hal jika kamu tetap sabar menjalaninya dengan baik.',
            'Tidak semua jawaban harus ditemukan hari ini, nikmati saja proses pencariannya.',
            'Bersyukur setiap hari akan membuat hidup terasa lebih damai dan penuh makna.',
            'Masa lalu memang tidak berubah, tetapi masa depan selalu menunggu keputusanmu hari ini.',
            'Jangan takut memulai kembali karena kesempatan baru selalu datang bersama keberanian.',
            'Hidup tidak meminta kesempurnaan, tetapi menghargai usaha yang dilakukan dengan sungguh-sungguh.',
            'Belajar memaafkan akan membuat hatimu jauh lebih tenang daripada menyimpan kebencian.',
            'Setiap pagi membawa kesempatan baru untuk menjadi pribadi yang lebih baik.',
            'Kesabaran bukan menunggu tanpa usaha, melainkan tetap berjuang dengan penuh keyakinan.',
            'Jangan biarkan satu kegagalan menghentikan semua impian yang telah kamu bangun.',
            'Perubahan besar selalu dimulai dari keputusan kecil yang dilakukan dengan konsisten.',
            'Tidak semua orang akan memahami perjalanan hidup yang sedang kamu jalani sekarang.',
            'Jadilah dirimu sendiri tanpa takut kehilangan penerimaan dari orang lain.',
            'Bahagia tidak selalu berasal dari memiliki, tetapi juga dari rasa cukup.',
            'Jangan membuang waktumu hanya untuk memenuhi harapan yang bukan milikmu sendiri.',
            'Kejujuran mungkin terasa sulit, tetapi selalu menghasilkan ketenangan dalam kehidupan.',
            'Mimpi besar membutuhkan keberanian untuk memulai meski belum merasa benar-benar siap.',
            'Setiap tantangan yang datang membawa kesempatan baru untuk terus bertumbuh menjadi lebih baik.',
            'Belajar mencintai diri sendiri adalah awal dari hubungan yang sehat dengan orang lain.',
            'Jangan takut berbeda karena setiap orang memiliki jalan hidup yang tidak sama.',
            'Keikhlasan membantu hati menerima hal-hal yang memang tidak bisa diubah lagi.',
            'Hidup akan terus berjalan meskipun semua rencana tidak berjalan sesuai harapan.',
            'Jangan pernah meremehkan dampak baik dari tindakan kecil yang dilakukan setiap hari.',
            'Semua orang sedang berjuang dengan cerita yang mungkin tidak pernah kamu ketahui.',
            'Fokus pada pertumbuhanmu sendiri tanpa sibuk membandingkan kehidupan dengan orang lain.',
            'Tidak ada kata terlambat untuk belajar, berkembang, dan memperbaiki diri menjadi lebih baik.',
            'Berani meminta bantuan menunjukkan bahwa kamu menghargai dirimu sendiri dengan bijaksana.',
            'Jangan biarkan rasa takut mengambil keputusan menggantikan impian yang ingin diwujudkan.',
            'Hidup akan terasa lebih damai ketika kamu berhenti mengendalikan semua hal.',
            'Setiap keberhasilan besar selalu diawali oleh keberanian mengambil langkah pertama yang sederhana.',
            'Kesuksesan bukan hanya tentang hasil, tetapi juga proses yang membentuk karaktermu.',
            'Tetaplah rendah hati meskipun pencapaianmu mulai melampaui banyak orang di sekitarmu.',
            'Jangan kehilangan harapan karena keadaan buruk tidak akan berlangsung selamanya dalam hidup.',
            'Senyuman tulus mampu menghadirkan kehangatan bahkan di tengah hari yang melelahkan.',
            'Belajar menerima kritik akan membantumu tumbuh menjadi pribadi yang lebih dewasa.',
            'Jangan berhenti bermimpi hanya karena pernah gagal mewujudkannya di masa lalu.',
            'Percayalah bahwa setiap usaha baik akan menemukan hasil terbaik pada waktunya.',
            'Teruslah bertumbuh setiap hari karena versi terbaikmu masih menunggu untuk ditemukan.',
            'Jangan takut mengambil jalan berbeda karena setiap perjalanan memiliki tujuan yang tidak selalu sama.',
            'Kebahagiaan sejati hadir ketika kamu mampu menerima dirimu tanpa syarat dari siapa pun.',
            'Hidup akan terasa lebih indah saat kamu berhenti memikirkan penilaian orang lain.',
            'Jangan menyerah pada keadaan, karena badai terkuat sekalipun pasti akan berlalu suatu saat.',
            'Kesempatan baru sering datang setelah kamu berani melepaskan sesuatu yang sudah usang.',
            'Tidak semua kehilangan berarti kegagalan, terkadang itu adalah awal dari kebahagiaan baru.',
            'Bersyukur atas hal sederhana mampu membuat hati lebih tenang menghadapi berbagai tantangan hidup.',
            'Jangan menunggu waktu yang sempurna, karena waktu terbaik adalah saat kamu memulai sekarang.',
            'Kesabaran bukan menunda impian, melainkan tetap percaya saat hasil belum terlihat nyata.',
            'Jangan biarkan rasa takut menghalangi langkah menuju kehidupan yang selama ini kamu impikan.',
            'Orang yang paling mengenal dirimu adalah dirimu sendiri, maka dengarkan suara hatimu.',
            'Tidak semua pertanyaan membutuhkan jawaban, beberapa cukup dipahami melalui pengalaman hidup.',
            'Teruslah belajar meskipun merasa tertinggal, karena setiap orang memiliki kecepatan yang berbeda.',
            'Hidup mengajarkan bahwa ketulusan selalu lebih berharga daripada pencitraan yang sementara.',
            'Jangan memaksakan semua orang bertahan, karena tidak semua perjalanan harus ditempuh bersama.',
            'Kesuksesan bukan milik mereka yang sempurna, tetapi mereka yang tidak mudah menyerah.',
            'Hargai setiap proses kecil karena pencapaian besar selalu dimulai dari langkah sederhana.',
            'Berhenti membandingkan hidupmu, karena setiap orang memiliki cerita yang tidak sama.',
            'Jadilah pribadi yang memberi manfaat meskipun tidak selalu mendapatkan penghargaan dari orang lain.',
            'Jangan biarkan kegagalan kemarin menentukan keputusan yang akan kamu ambil hari ini.',
            'Semakin dewasa, kamu akan memahami bahwa ketenangan jauh lebih berharga daripada kemenangan.',
            'Memaafkan bukan berarti melupakan, tetapi membebaskan dirimu dari beban yang menyakitkan.',
            'Jangan terlalu keras kepada diri sendiri, karena kamu juga pantas mendapatkan pengertian.',
            'Setiap impian membutuhkan keberanian untuk bertahan ketika keadaan mulai terasa sangat sulit.',
            'Hidup selalu menawarkan kesempatan baru bagi mereka yang mau terus mencoba lagi.',
            'Jangan takut berubah karena pertumbuhan selalu membutuhkan keberanian meninggalkan zona nyaman.',
            'Orang baik tidak selalu menang cepat, tetapi mereka tetap memenangkan ketenangan hidup.',
            'Belajar menerima kekurangan adalah langkah penting menuju kehidupan yang lebih bahagia.',
            'Tidak semua pintu yang tertutup adalah penolakan, terkadang itu adalah perlindungan terbaik.',
            'Tetaplah rendah hati meskipun pencapaianmu mulai membuat banyak orang mengagumimu.',
            'Jangan biarkan rasa kecewa membuatmu kehilangan kemampuan untuk kembali mempercayai kehidupan.',
            'Semua perjalanan hebat dimulai dari keberanian mengambil satu langkah kecil setiap hari.',
            'Hidup tidak pernah terlambat memberikan kesempatan selama kamu masih mau terus berusaha.',
            'Bahagia bukan tentang memiliki segalanya, tetapi mensyukuri apa yang sudah dimiliki sekarang.',
            'Jangan takut berjalan sendiri jika itu membawamu menuju kehidupan yang lebih baik.',
            'Luka yang sembuh akan menjadi pengingat bahwa kamu pernah berhasil melewati masa sulit.',
            'Kejujuran mungkin terasa berat, tetapi selalu menghadirkan kedamaian dalam jangka waktu panjang.',
            'Jangan menyesali waktu yang berlalu, jadikan pengalaman itu sebagai bekal untuk bertumbuh.',
            'Orang yang sabar bukan lemah, tetapi mampu mengendalikan dirinya dalam berbagai keadaan.',
            'Teruslah melangkah meskipun hasilnya belum terlihat sesuai dengan harapan yang kamu miliki.',
            'Hidup tidak selalu adil, tetapi selalu memberikan pelajaran bagi mereka yang mau belajar.',
            'Jangan takut gagal berkali-kali karena setiap kegagalan membawa pengalaman yang sangat berharga.',
            'Percaya kepada proses akan membuatmu lebih kuat menghadapi berbagai perubahan dalam kehidupan.',
            'Jangan menunggu pengakuan orang lain untuk merasa bahwa dirimu sudah cukup berharga.',
            'Keberanian terbesar adalah tetap menjadi dirimu sendiri di tengah banyaknya tuntutan dunia.',
            'Tidak semua kebahagiaan harus diumumkan, beberapa cukup dirasakan dengan hati yang tenang.',
            'Belajar mengikhlaskan akan membuka ruang bagi kebahagiaan baru dalam kehidupanmu.',
            'Jadikan setiap hari sebagai kesempatan untuk menjadi pribadi yang lebih baik dari kemarin.',
            'Impian tidak akan mendekat jika kamu hanya menunggu tanpa mengambil tindakan nyata.',
            'Tetaplah berharap, karena selalu ada alasan baru untuk tersenyum pada hari esok.',
            'Jangan takut memulai dari nol, karena semua pencapaian besar pernah berada di titik itu.',
            'Hidup menjadi lebih ringan ketika kamu berhenti membawa penyesalan yang sudah berlalu terlalu lama.',
            'Tidak semua orang akan tinggal, tetapi setiap pertemuan selalu meninggalkan pelajaran yang berharga.',
            'Keberhasilan sejati lahir dari kebiasaan kecil yang dilakukan dengan penuh konsistensi setiap hari.',
            'Jangan biarkan rasa malu menghalangi kesempatan untuk belajar hal-hal yang benar-benar baru.',
            'Bahagia bukan tujuan akhir, melainkan cara menikmati setiap langkah dalam perjalanan hidupmu.',
            'Kesulitan hari ini sedang mempersiapkanmu menghadapi kesempatan besar yang akan segera datang.',
            'Belajarlah mendengarkan sebelum berbicara agar hubunganmu dengan orang lain menjadi lebih baik.',
            'Tidak semua jawaban berasal dari orang lain, beberapa hanya ditemukan dalam dirimu sendiri.',
            'Jadikan kegagalan sebagai pijakan, bukan alasan untuk berhenti mengejar impian yang kamu miliki.',
            'Hidup akan terasa damai ketika kamu berhenti mengejar validasi dari setiap orang.',
            'Setiap keputusan yang bijaksana selalu diawali dengan pikiran yang tenang dan hati yang jernih.',
            'Jangan menyerah hanya karena perjalananmu lebih lambat dibandingkan orang lain di sekitarmu.',
            'Orang yang terus belajar akan selalu menemukan peluang di tengah berbagai perubahan kehidupan.',
            'Jangan takut kehilangan orang yang tidak pernah benar-benar menghargai keberadaanmu sejak awal.',
            'Setiap tantangan mengajarkan kemampuan baru yang mungkin belum pernah kamu sadari sebelumnya.',
            'Bersikap baik kepada orang lain juga berarti menghormati nilai yang ada dalam dirimu.',
            'Hidup bukan tentang siapa tercepat, tetapi siapa yang mampu bertahan hingga akhir perjalanan.',
            'Jangan memaksakan semua hal berjalan sempurna karena hidup memang penuh dengan kejutan.',
            'Keberanian tumbuh ketika kamu memilih melangkah meski belum mengetahui seluruh jawabannya.',
            'Jangan meragukan kemampuanmu hanya karena orang lain belum pernah melihat potensimu.',
            'Kesabaran adalah investasi yang sering menghasilkan kebahagiaan pada waktu yang tidak terduga.',
            'Belajar mengendalikan emosi akan membantumu mengambil keputusan yang lebih bijaksana setiap hari.',
            'Jangan berhenti bermimpi hanya karena keadaan saat ini belum sesuai dengan harapanmu.',
            'Setiap orang memiliki waktu terbaiknya sendiri, maka berhentilah membandingkan perjalanan hidupmu.',
            'Hidup mengajarkan bahwa ketulusan akan selalu menemukan jalannya meskipun membutuhkan waktu lebih lama.',
            'Jangan biarkan satu kegagalan membuatmu melupakan semua keberhasilan yang pernah diraih sebelumnya.',
            'Orang yang kuat bukan tidak pernah menangis, melainkan selalu bangkit setelah terluka.',
            'Tetaplah menghargai dirimu meskipun belum semua orang memahami perjuangan yang sedang kamu jalani.',
            'Jangan takut berubah menjadi lebih baik meskipun harus meninggalkan kebiasaan yang lama.',
            'Bahagia dimulai ketika kamu menerima bahwa tidak semua hal bisa kamu kendalikan.',
            'Hidup memberikan pelajaran terbaik melalui pengalaman yang terkadang terasa sangat menyakitkan.',
            'Jangan mengorbankan kedamaian hanya demi memenuhi harapan yang bukan berasal dari dirimu.',
            'Setiap langkah kecil yang dilakukan hari ini sedang membangun masa depan yang lebih baik.',
            'Kepercayaan diri tumbuh ketika kamu menghargai proses, bukan hanya mengejar hasil akhir.',
            'Jangan takut berkata tidak jika itu menjaga kesehatan hati dan pikiranmu.',
            'Orang yang rendah hati akan selalu memiliki ruang untuk terus belajar dan berkembang.',
            'Tidak semua kesempatan datang dua kali, maka manfaatkan setiap peluang dengan sebaik mungkin.',
            'Belajar menerima kenyataan akan membuatmu lebih kuat menghadapi berbagai perubahan dalam kehidupan.',
            'Jangan membiarkan masa lalu mencuri kebahagiaan yang sedang kamu miliki hari ini.',
            'Keberhasilan yang paling indah adalah ketika kamu tetap menjadi pribadi yang rendah hati.',
            'Jangan berhenti mencoba meskipun hasilnya belum sesuai dengan harapan yang kamu inginkan.',
            'Semua perjuangan yang tulus akan menemukan waktunya untuk menghasilkan sesuatu yang berharga.',
            'Hidup menjadi lebih bermakna ketika kamu mampu berbagi kebaikan tanpa mengharapkan balasan.',
            'Jangan takut berjalan perlahan selama kamu tidak berhenti menuju tujuan yang diimpikan.',
            'Setiap hari adalah kesempatan baru untuk memperbaiki kesalahan tanpa harus menyalahkan diri sendiri.',
            'Belajarlah mencintai proses karena hasil terbaik selalu membutuhkan waktu yang tidak sebentar.',
            'Jangan menunggu semuanya sempurna untuk mulai menciptakan perubahan dalam kehidupanmu sendiri.',
            'Orang yang terus bertumbuh tidak pernah berhenti belajar dari pengalaman sekecil apa pun.',
            'Percayalah, setiap langkah baik yang kamu ambil akan membawa kehidupan menuju arah terbaik.',
            'Jangan takut menjadi dirimu sendiri, karena keaslian selalu lebih berharga daripada kepura-puraan.',
            'Setiap kegagalan yang kamu alami sedang membentuk versi dirimu yang lebih bijaksana.',
            'Hidup tidak pernah berhenti memberi kesempatan kepada mereka yang masih mau berusaha.',
            'Jangan menunggu keberanian datang, karena keberanian tumbuh setelah kamu mulai melangkah.',
            'Orang yang menghargai proses akan menikmati hasil tanpa kehilangan rasa syukur.',
            'Tidak semua rencana berjalan mulus, tetapi setiap perjalanan selalu memiliki makna tersendiri.',
            'Jangan terlalu sibuk mengejar dunia hingga lupa menikmati momen sederhana dalam hidup.',
            'Kebaikan yang dilakukan dengan tulus akan kembali melalui cara yang tidak terduga.',
            'Belajar mengalah bukan berarti kalah, terkadang itu adalah pilihan yang paling bijaksana.',
            'Jangan biarkan rasa takut mencuri kesempatan yang seharusnya menjadi milikmu.',
            'Hidup mengajarkan bahwa kesabaran sering kali menghasilkan sesuatu yang jauh lebih indah.',
            'Tidak semua orang akan memahami pilihanmu, tetaplah berjalan sesuai nilai yang kamu yakini.',
            'Setiap hari adalah halaman baru untuk menulis kisah hidup yang lebih bermakna.',
            'Jangan mengukur nilai dirimu dari pendapat orang yang tidak mengenal perjuanganmu.',
            'Menerima diri sendiri adalah langkah pertama menuju kehidupan yang lebih damai.',
            'Tidak ada perjalanan yang sia-sia jika kamu mampu mengambil pelajaran dari setiap langkah.',
            'Jangan berhenti berharap meskipun kenyataan belum sesuai dengan doa yang kamu panjatkan.',
            'Orang yang terus belajar akan selalu menemukan jalan di tengah berbagai kesulitan.',
            'Hidup bukan perlombaan, maka nikmatilah setiap proses tanpa terburu-buru mengejar tujuan.',
            'Jangan takut gagal karena setiap keberhasilan selalu memiliki cerita tentang kegagalan sebelumnya.',
            'Kesederhanaan sering menghadirkan kebahagiaan yang tidak mampu dibeli oleh kekayaan.',
            'Jangan mengabaikan suara hatimu hanya demi memenuhi keinginan orang lain.',
            'Kepercayaan dibangun melalui kejujuran yang dijaga dalam setiap keadaan kehidupan.',
            'Semua impian besar dimulai dari keberanian mengambil langkah kecil yang pertama.',
            'Jangan memandang rendah dirimu hanya karena perjalananmu lebih lambat daripada orang lain.',
            'Hidup menjadi lebih indah ketika kamu belajar bersyukur atas hal-hal yang sederhana.',
            'Jangan membawa kemarahan terlalu lama karena hanya akan melelahkan hati dan pikiran.',
            'Orang yang mampu bangkit setelah jatuh memiliki kekuatan yang tidak semua orang miliki.',
            'Jangan takut kehilangan sesuatu yang menghalangi pertumbuhanmu menjadi pribadi yang lebih baik.',
            'Bahagia bukan tentang memiliki segalanya, tetapi menghargai apa yang sudah dimiliki saat ini.',
            'Setiap tantangan membawa kesempatan untuk menemukan kemampuan yang belum pernah kamu sadari.',
            'Jangan biarkan masa lalu menghalangi langkahmu menuju masa depan yang lebih cerah.',
            'Orang yang rendah hati akan selalu menemukan ruang untuk terus berkembang setiap hari.',
            'Hidup akan terasa lebih ringan ketika kamu berhenti memikirkan hal di luar kendali.',
            'Jangan menunda perubahan hanya karena merasa belum siap menghadapi berbagai kemungkinan.',
            'Semua pencapaian besar membutuhkan waktu, kesabaran, dan usaha yang tidak sedikit.',
            'Jangan biarkan rasa kecewa menghapus semua harapan yang pernah kamu bangun sebelumnya.',
            'Belajar mendengarkan dengan tulus sering kali lebih bermakna daripada berbicara panjang lebar.',
            'Hidup akan selalu memberi pelajaran kepada mereka yang mau membuka hati untuk belajar.',
            'Jangan takut berjalan sendirian jika jalan itu membawa kehidupan yang lebih baik.',
            'Kebaikan kecil yang dilakukan setiap hari mampu memberikan perubahan besar dalam kehidupan.',
            'Jangan mengorbankan kebahagiaanmu hanya demi menyenangkan semua orang di sekitarmu.',
            'Orang yang sabar mampu melihat harapan bahkan ketika keadaan terlihat sangat sulit.',
            'Setiap langkah yang kamu ambil hari ini sedang menentukan masa depanmu perlahan-lahan.',
            'Jangan berhenti berkembang hanya karena merasa sudah cukup mengetahui banyak hal.',
            'Hidup mengajarkan bahwa ketenangan jauh lebih berharga daripada kemenangan yang dipenuhi ego.',
            'Tidak semua perpisahan menyakitkan, beberapa justru membuka jalan menuju kehidupan yang lebih baik.',
            'Jangan takut mencoba kembali karena kesempatan baru selalu hadir bagi mereka yang berani.',
            'Semua perjuangan yang dilakukan dengan tulus akan menemukan hasil terbaik pada waktunya.',
            'Jadilah alasan seseorang kembali percaya bahwa dunia masih memiliki banyak kebaikan.',
            'Jangan menyerah pada keadaan, karena setiap badai pasti akan menemukan akhir yang tenang.',
            'Hidup menjadi lebih bermakna ketika kamu belajar menikmati perjalanan, bukan hanya tujuan akhirnya.',
            'Tidak semua impian tercapai dengan cepat, tetapi semuanya membutuhkan ketekunan yang konsisten setiap hari.',
            'Jangan takut mengambil keputusan sulit demi kehidupan yang lebih damai dan bermakna.',
            'Orang yang menghargai waktu akan lebih mudah menghargai setiap kesempatan yang datang.',
            'Belajar menerima kenyataan adalah awal dari kehidupan yang lebih tenang dan bahagia.',
            'Jangan biarkan keraguan menghalangi langkahmu menuju impian yang telah lama diperjuangkan.',
            'Kesuksesan bukan hanya soal hasil, tetapi tentang pribadi yang terbentuk selama berjuang.',
            'Hidup selalu memberikan harapan baru kepada mereka yang tidak berhenti mencoba kembali.',
            'Jangan membiarkan satu kegagalan menghapus semua usaha baik yang telah kamu lakukan.',
            'Keberanian terbesar adalah memilih bangkit ketika hidup terasa begitu melelahkan dan berat.',
            'Jangan terlalu keras kepada dirimu karena setiap orang memiliki proses yang berbeda.',
            'Semua perjuangan akan terasa berarti ketika dilakukan dengan hati yang penuh keikhlasan.',
            'Hidup mengajarkan bahwa kesabaran sering menghasilkan sesuatu yang lebih indah dari harapan.',
            'Jangan takut meminta maaf karena kerendahan hati menunjukkan kekuatan yang sesungguhnya.',
            'Orang yang terus belajar tidak pernah benar-benar tertinggal dari perjalanan kehidupan.',
            'Bahagia bukan ditemukan, tetapi diciptakan melalui cara kita memandang setiap keadaan hidup.',
            'Jangan menghabiskan waktumu mengejar kesempurnaan hingga lupa menikmati setiap proses yang ada.',
            'Setiap pengalaman pahit akan menjadi bekal berharga untuk menghadapi masa depan dengan bijaksana.',
            'Jangan membandingkan perjuanganmu dengan orang lain yang memiliki jalan hidup berbeda.',
            'Hidup akan terasa lebih damai ketika kamu berhenti menyenangkan semua orang sekaligus.',
            'Tidak semua pintu yang tertutup adalah kegagalan, terkadang itu bentuk perlindungan terbaik.',
            'Belajar bersyukur membuat hati tetap tenang meskipun keadaan belum sesuai dengan harapan.',
            'Jangan takut memulai kembali karena setiap awal baru membawa kesempatan yang berbeda.',
            'Orang yang rendah hati selalu memiliki ruang untuk terus bertumbuh sepanjang hidupnya.',
            'Hidup bukan tentang siapa yang paling cepat, tetapi siapa yang tetap bertahan.',
            'Jangan menyerah hanya karena perjalananmu terasa lebih panjang daripada milik orang lain.',
            'Setiap tantangan membawa pelajaran yang tidak akan ditemukan dalam kehidupan yang mudah.',
            'Keikhlasan membantu hati menerima hal-hal yang memang tidak bisa lagi dipertahankan.',
            'Jangan takut berubah karena perubahan adalah bagian alami dari pertumbuhan setiap manusia.',
            'Semua keputusan hari ini akan menentukan arah kehidupanmu pada masa yang akan datang.',
            'Hidup mengajarkan bahwa kebahagiaan sederhana sering lebih bermakna daripada kemewahan yang berlebihan.',
            'Jangan biarkan rasa kecewa menghalangi langkah menuju kesempatan yang lebih baik.',
            'Orang yang mampu mengendalikan dirinya akan lebih mudah menghadapi berbagai masalah kehidupan.',
            'Tidak ada usaha yang benar-benar sia-sia jika dilakukan dengan niat yang baik.',
            'Jangan terlalu sibuk mengejar masa depan hingga melupakan kebahagiaan yang ada hari ini.',
            'Kepercayaan diri tumbuh ketika kamu berani menerima segala kekurangan yang dimiliki.',
            'Hidup menjadi lebih ringan saat kamu belajar melepaskan hal yang tidak bisa dikendalikan.',
            'Jangan takut gagal karena setiap kegagalan membawa pengalaman yang sangat berharga.',
            'Orang yang tulus akan selalu meninggalkan kesan baik di mana pun berada.',
            'Jangan menunggu motivasi datang, mulailah bergerak agar semangat mengikuti langkahmu perlahan.',
            'Semua mimpi besar selalu diawali oleh keberanian mengambil langkah yang sangat sederhana.',
            'Hidup tidak selalu mudah, tetapi selalu memberikan alasan untuk tetap berharap setiap hari.',
            'Jangan mengorbankan kesehatan demi kesuksesan yang tidak mampu kamu nikmati nantinya.',
            'Orang yang sabar mampu melihat peluang bahkan ketika keadaan tampak begitu sulit.',
            'Setiap langkah kecil yang konsisten akan membawamu lebih dekat kepada tujuan yang diimpikan.',
            'Jangan takut mengatakan tidak pada hal yang merusak ketenangan hidupmu sendiri.',
            'Hidup akan terasa lebih indah ketika kamu berbagi kebaikan tanpa mengharapkan balasan.',
            'Teruslah berkembang karena versi terbaik dirimu masih menunggu untuk benar-benar ditemukan.',
            'Percayalah, semua usaha baik yang kamu lakukan akan menemukan waktunya untuk berbuah indah.',
            'Jangan takut melangkah perlahan, karena kemajuan kecil tetap lebih baik daripada diam selamanya.',
            'Hidup akan selalu memberi kesempatan baru kepada mereka yang memilih bangkit setelah jatuh.',
            'Tidak semua perjalanan mudah, tetapi semuanya mampu membentuk pribadi yang lebih kuat dan bijaksana.',
            'Jangan mengukur kebahagiaanmu dari pencapaian orang lain yang memiliki jalan hidup berbeda.',
            'Kesabaran mengajarkan bahwa waktu terbaik sering datang setelah penantian yang cukup panjang.',
            'Jangan biarkan kegagalan hari ini menghalangi keberhasilan yang mungkin datang esok hari.',
            'Semua orang memiliki perjuangan yang tidak terlihat, maka perlakukanlah mereka dengan penuh kebaikan.',
            'Hidup terasa lebih ringan ketika kamu berhenti membawa beban yang sudah seharusnya dilepaskan.',
            'Jangan takut mencoba lagi karena setiap kesempatan baru membawa kemungkinan yang lebih baik.',
            'Bahagia bukan tentang memiliki semuanya, tetapi menghargai apa yang sudah ada hari ini.',
            'Orang yang mampu mengendalikan emosinya akan lebih mudah menghadapi berbagai tantangan kehidupan.',
            'Jangan menunggu orang lain percaya kepadamu, mulailah dengan mempercayai kemampuan dirimu sendiri.'.
            'Semua pencapaian besar selalu membutuhkan kesabaran, ketekunan, dan keyakinan yang tidak mudah goyah.',
            'Hidup mengajarkan bahwa ketulusan sering kali lebih berharga daripada kepintaran semata.',
            'Jangan takut mengambil keputusan yang benar meskipun tidak disukai oleh banyak orang.',
            'Setiap hari adalah kesempatan baru untuk memperbaiki kesalahan tanpa terus menyalahkan diri sendiri.',
            'Jangan terlalu sibuk mengejar masa depan hingga melupakan kebahagiaan yang hadir saat ini.',
            'Orang yang bersyukur akan menemukan kebahagiaan bahkan dalam keadaan yang sangat sederhana.',
            'Jangan menyerah pada impianmu hanya karena perjalanan terasa lebih sulit dari perkiraan.',
            'Hidup akan selalu berubah, maka belajarlah menyesuaikan diri tanpa kehilangan nilai kehidupanmu.',
            'Tidak semua perpisahan membawa kesedihan, beberapa justru membuka jalan menuju kebahagiaan baru.',
            'Jangan biarkan rasa takut menghentikan langkah yang sebenarnya mampu membawamu menuju keberhasilan.',
            'Semua pengalaman, baik maupun buruk, memiliki pelajaran yang berguna untuk masa depanmu.',
            'Hidup menjadi lebih damai ketika kamu menerima bahwa tidak semua hal bisa dikendalikan.',
            'Jangan takut terlihat berbeda karena setiap keunikan memiliki nilai yang sangat berharga.',
            'Orang yang terus belajar akan selalu menemukan cara menghadapi perubahan dengan lebih bijaksana.',
            'Jangan membalas keburukan dengan keburukan karena ketenangan lebih bernilai daripada pembalasan.',
            'Setiap kesulitan sedang mempersiapkanmu menjadi pribadi yang lebih kuat menghadapi kehidupan mendatang.',
            'Jangan terlalu lama menyesali masa lalu karena masa depan masih menunggu untuk diperjuangkan.',
            'Hidup tidak meminta kesempurnaan, tetapi menghargai usaha yang dilakukan dengan sepenuh hati.',
            'Jangan membuang energimu untuk hal-hal yang tidak membawa manfaat bagi kehidupanmu sendiri.',
            'Semua langkah kecil yang dilakukan dengan konsisten akan menghasilkan perubahan besar suatu hari.',
            'Jangan takut gagal berkali-kali karena keberhasilan sering lahir dari banyak percobaan sebelumnya.',
            'Hidup akan terasa lebih indah ketika kamu belajar berbagi tanpa mengharapkan imbalan apa pun.',
            'Jangan biarkan perkataan orang lain menentukan seberapa besar kamu menghargai dirimu sendiri.',
            'Orang yang rendah hati akan selalu dihormati karena sikapnya, bukan karena pencapaiannya.',
            'Semua impian membutuhkan keberanian untuk bertahan ketika keadaan mulai terasa sangat sulit.',
            'Jangan terlalu cepat menyerah karena hasil terbaik sering datang pada usaha terakhir.',
            'Hidup mengajarkan bahwa kejujuran selalu membawa ketenangan meskipun terkadang terasa menyakitkan.',
            'Jangan mengorbankan kedamaian batin hanya demi memenuhi harapan yang bukan milikmu sendiri.',
            'Orang yang mampu memaafkan akan hidup lebih tenang daripada mereka yang menyimpan dendam.',
            'Semua perjalanan hidup memiliki waktunya sendiri, maka berhentilah terburu-buru membandingkan diri.',
            'Jangan takut memulai kembali karena setiap awal selalu membawa peluang yang belum pernah ada.',
            'Hidup akan selalu memberikan alasan baru untuk berharap kepada mereka yang tidak menyerah.',
            'Jangan membatasi dirimu dengan keraguan yang sebenarnya hanya berasal dari pikiran sendiri.',
            'Orang yang mampu menghargai proses akan lebih menikmati setiap pencapaian yang diraihnya.',
            'Semua kebaikan yang kamu tanam hari ini akan kembali dalam bentuk yang tidak terduga.',
            'Jangan berhenti berkembang hanya karena merasa sudah mencapai banyak hal dalam kehidupan.',
            'Hidup menjadi lebih bermakna ketika kamu memilih memberi manfaat bagi orang-orang di sekitarmu.',
            'Percayalah, setiap perjuangan yang dilakukan dengan tulus akan menemukan hasil terbaik pada waktunya.',
            'Jangan takut bermimpi besar karena setiap pencapaian luar biasa selalu diawali oleh sebuah keyakinan.',
            'Hidup mengajarkan bahwa kebahagiaan sejati tumbuh dari hati yang mampu bersyukur setiap hari.',
            'Jangan menyerah pada keadaan karena setiap kesulitan pasti memiliki batas akhirnya sendiri.',
            'Semua perjalanan hidup akan terasa indah ketika dijalani dengan hati yang penuh keikhlasan.',
            'Jangan terlalu sibuk mengejar dunia hingga melupakan kebahagiaan sederhana yang sudah dimiliki.',
            'Orang yang terus berusaha akan selalu memiliki peluang lebih besar untuk berhasil nantinya.',
            'Hidup bukan tentang menghindari masalah, tetapi belajar menjadi lebih kuat menghadapinya bersama waktu.',
            'Jangan takut meminta pertolongan karena setiap manusia pernah membutuhkan orang lain dalam hidupnya.',
            'Semua luka akan perlahan sembuh ketika kamu memilih berdamai dengan kenyataan yang ada.',
            'Jangan biarkan satu kegagalan membuatmu melupakan semua kemampuan yang telah kamu miliki.',
            'Hidup selalu memberi pelajaran baru kepada mereka yang mau membuka hati untuk belajar.',
            'Jangan mengukur keberhasilan hanya dari materi, tetapi juga dari ketenangan yang dirasakan.',
            'Semua orang memiliki waktu terbaiknya sendiri, maka berhentilah terburu-buru mengejar pencapaian orang lain.',
            'Jangan takut berjalan perlahan selama langkahmu tetap mengarah kepada tujuan yang benar.',
            'Hidup menjadi lebih damai ketika kamu belajar menerima segala sesuatu dengan hati yang lapang.',
            'Jangan menunggu kesempatan datang jika kamu mampu menciptakan peluang melalui usaha yang konsisten.',
            'Semua pengalaman hidup akan menjadi bekal berharga jika kamu mampu mengambil hikmahnya.',
            'Jangan terlalu keras kepada dirimu karena setiap proses membutuhkan waktu untuk berkembang.',
            'Hidup akan terasa lebih ringan ketika kamu berhenti memikirkan hal yang di luar kendali.',
            'Jangan takut berubah karena pertumbuhan selalu membutuhkan keberanian meninggalkan kebiasaan lama.',
            'Semua perjuangan yang dilakukan dengan sabar akan menemukan hasil terbaik pada waktunya nanti.',
            'Jangan biarkan rasa kecewa menghapus semangatmu untuk kembali mencoba dan memperbaiki diri.',
            'Hidup mengajarkan bahwa ketulusan selalu lebih berharga daripada pencitraan yang sementara.',
            'Jangan takut gagal lagi karena pengalamanmu sekarang lebih banyak daripada sebelumnya.',
            'Semua langkah kecil yang dilakukan setiap hari akan membentuk perubahan besar di masa depan.',
            'Jangan membandingkan hidupmu dengan orang lain yang memiliki cerita dan perjuangan berbeda.',
            'Hidup akan menjadi lebih bermakna ketika kamu mampu memberi manfaat bagi sesama.',
            'Jangan mengorbankan kedamaian hati demi mendapatkan pengakuan dari orang yang salah.',
            'Semua impian layak diperjuangkan selama kamu masih memiliki keyakinan untuk melangkah maju.',
            'Jangan menyerah hanya karena hasil belum terlihat sesuai dengan harapan yang kamu miliki.',
            'Hidup tidak pernah terlambat memberikan kesempatan kepada mereka yang tetap percaya dan berusaha.',
            'Jangan takut kehilangan sesuatu yang memang bukan ditakdirkan untuk tetap bersamamu.',
            'Semua tantangan akan terasa lebih ringan ketika dihadapi dengan pikiran yang tenang.',
            'Jangan membiarkan rasa takut menghalangi kesempatan yang mampu mengubah masa depanmu.',
            'Hidup selalu menyediakan harapan baru meskipun hari ini terasa begitu melelahkan.',
            'Jangan terlalu fokus pada kekurangan hingga melupakan semua kelebihan yang telah dimiliki.',
            'Semua orang pernah gagal, tetapi tidak semua orang memilih bangkit untuk mencoba kembali.',
            'Jangan menunda kebahagiaan hanya karena menunggu segala sesuatu menjadi sempurna.',
            'Hidup akan terasa lebih indah ketika dijalani dengan rasa syukur dan ketulusan hati.',
            'Jangan takut memulai kembali karena setiap awal baru selalu membawa kemungkinan terbaik.',
            'Semua keputusan kecil yang kamu ambil hari ini akan membentuk masa depanmu perlahan.',
            'Jangan menghabiskan hidup untuk menyenangkan semua orang hingga melupakan dirimu sendiri.',
            'Hidup mengajarkan bahwa kesabaran sering menjadi jalan menuju keberhasilan yang paling indah.',
            'Jangan menyerah sebelum memberikan kesempatan terbaik kepada dirimu untuk terus berkembang.',
            'Semua usaha yang dilakukan dengan sepenuh hati akan meninggalkan hasil yang membanggakan.',
            'Jangan biarkan penilaian orang lain menentukan seberapa besar kamu menghargai dirimu.',
            'Hidup akan terasa lebih damai ketika kamu belajar memaafkan tanpa terus mengingat kesalahan.',
            'Jangan takut mengambil langkah pertama karena semua perjalanan besar selalu dimulai dari sana.',
            'Semua kebaikan yang kamu lakukan akan kembali pada waktu yang tidak pernah diduga.',
            'Jangan pernah berhenti belajar karena kehidupan selalu menyediakan pelajaran yang baru setiap hari.',
            'Hidup menjadi lebih berarti ketika kamu memilih tumbuh daripada terus menyalahkan keadaan.',
            'Jangan takut menghadapi perubahan karena setiap perubahan membawa kesempatan untuk berkembang.',
            'Semua keberhasilan besar membutuhkan ketekunan yang mampu bertahan melewati berbagai kesulitan.',
            'Jangan membiarkan masa lalu menghalangi kebahagiaan yang sedang menantimu di masa depan.',
            'Hidup akan selalu memberikan alasan baru untuk tersenyum kepada mereka yang berharap.',
            'Jangan takut berbeda karena keunikanmu adalah kekuatan yang tidak dimiliki semua orang.',
            'Semua perjuangan yang dijalani dengan ikhlas akan terasa lebih ringan dan bermakna.',
            'Jangan menunggu sempurna untuk memulai karena kesempurnaan lahir dari proses belajar.',
            'Hidup mengajarkan bahwa ketenangan jauh lebih berharga daripada kemenangan yang dipenuhi ego.',
            'Jangan menyerah pada impianmu karena langkah kecil hari ini menentukan masa depanmu.',
            'Semua perjalanan memiliki waktunya sendiri, maka nikmatilah proses tanpa terburu-buru membandingkan diri.',
            'Jangan takut jatuh karena setiap kali bangkit kamu menjadi pribadi yang lebih kuat.',
            'Hidup akan selalu menemukan cara menguatkan mereka yang memilih bertahan dengan harapan.',
            'Jangan pernah meragukan nilaimu hanya karena belum semua orang mampu melihat potensimu.',
            'Teruslah melangkah dengan penuh harapan karena versi terbaik dirimu masih menunggu di depan.',
        ];

        foreach ($insights as $index => $insight) {
            DailyInsight::create([
                'date' => Carbon::today()->addDays($index),
                'insight' => $insight,
            ]);
        }
    }
}